### ISSUE TITLE
ScriptEnviroment.Invoke causes memory leak

### ISSUE THREAD

**Issue by introspected** [mysteryx93/AvsFilterNet#3]
I have to call env.Invoke many times for each frame with different arguments and temporary clip chain.
Sample code:
```
        public override VideoFrame GetFrame(int n, ScriptEnvironment env)
        {
            using (new AVSValueCollector())
            using (new VideoFrameCollector())
            {
                var width = new Random(n).Next(4000, 5000);
                var args = new AVSValue(new AVSValue(Child), new AVSValue(width), new AVSValue(width / 2));
                using (var tmpClip = env.Invoke("BilinearResize", args).AsClip())
                {
                    var frame = tmpClip.GetFrame(n, env);
                    // some process here
                }
            }
            return base.GetFrame(n, env);
        }
```
It causes memory leak because temp clip is not disposed properly. 
Once I add `delete _pclip;` to AvsFilterNet.Clip.CleanUp() it works fine but causes AccessViolationException on program exit at this line (acceptable solution but not ideal).

**Comment by introspected** [comment]
> Once I add `delete _pclip;` to AvsFilterNet.Clip.CleanUp() it works fine but causes AccessViolationException on program exit at this line

The exception was thrown because I forgot to dispose all clips in my filter on exit which was passed as arguments. So `delete _pclip;` works well now.

**Comment by mysteryx93** [comment]
can you submit a Github fix so I can merge?

**Comment by introspected** [comment]
Sure: https://github.com/mysteryx93/AvsFilterNet/pull/4
